# Generated by Django 3.1.7 on 2021-04-19 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=240, null=True, verbose_name='фамилия')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='день рождения')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d', verbose_name='аватар')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
